services:
  postgres:
    image: postgres:16
    container_name: recette-postgres
    environment:
      POSTGRES_DB: recette_db
      POSTGRES_USER: recette_user
      POSTGRES_PASSWORD: recette_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
